server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.mySQLDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitylearn
    username: root
    password: EloTal100
  main:
    web-application-type: servlet
